# Generated by Django 4.0.3 on 2022-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_customer_gender_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default='Non-AC', max_length=50),
        ),
    ]
