# Generated by Django 4.0.3 on 2022-05-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_rooms_room_no_alter_rooms_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Payment_Type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_no',
            field=models.CharField(max_length=50),
        ),
    ]
