# Generated by Django 4.0.3 on 2022-05-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_end_day_alter_booking_start_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='name',
        ),
    ]
