# Generated by Django 4.0.3 on 2022-05-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_customer_name_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Payment_date',
            field=models.DateField(),
        ),
    ]
