# Generated by Django 4.0.3 on 2022-05-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.rooms'),
        ),
    ]
