# Generated by Django 4.0.3 on 2022-05-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_room_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_day',
            new_name='Check_In_day',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_day',
            new_name='Check_Out_day',
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
